name: Integração Contínua
on:
  workflow_dispatch:
    inputs:
      sonar:
        description: 'Defini se o sonar será executado'
        required: true
        default: true
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: ['3.8.8', '3.9.8']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: '21'
          cache: "maven"



      - name: mvn build
        run: |
          if mvn clean install; then
            status="Sucesso ✅" >> $GITHUB_ENV
          else
            status="Falha ❌" >> $GIThUB_ENV
          fi

      - name: Summary
        run: |
          echo "Resumo" >> $GITHUB_STEP_SUMMARY
          echo "Build: ${{ env.status }}" >> $GITHUB_STEP_SUMMARY
          
